package:
  name: geometric-smote
  version: "0.1.1"

source:
  git_rev: 0.1.1
  git_url: https://github.com/AlgoWit/geometric-smote

build:
  number: 0
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - scikit-learn >=0.21
    - imbalanced-learn >=0.4.3

  run:
    - python
    - scikit-learn >=0.21
    - imbalanced-learn >=0.4.3

test:
  requires:
    - coverage
    - pytest
    - pytest-cov
  imports:
    - gsmote

about:
  home: https://github.com/AlgoWit/geometric-smote
  license: MIT
  license_file: LICENSE
